extends RefCounted
## Japanese UI text. English source strings map to Japanese; unknown strings pass
## through unchanged so untranslated screens keep working while text is migrated.
##
## Static strings are translated by label_at() automatically. Formatted or
## concatenated strings must wrap their template: Loc.t("...") % [...].

const JA := {
	# --- Title screen ---
	"DEEP HUNTER": "深淵の狩人",
	"CONTINUE": "つづきから",
	"NEW GAME": "はじめから",
	"SETTINGS": "設定",
	"QUIT": "終了",
	"CHAPTER %d / LEVEL %d / %d MIN PLAYED": "第%d章 / Lv.%d / プレイ%d分",
	"NO SAVE DATA / START A NEW JOURNEY": "セーブデータなし / はじめから始めます",
	"W / S or ARROWS: choose     ENTER: confirm": "W/S または 矢印: 選択     ENTER: 決定",
	"OVERWRITE EXISTING SAVE?": "セーブデータを上書きしますか？",
	"This erases the current character.": "現在のキャラクターは消去されます。",
	"Y / ENTER: erase     N / ESC: cancel": "Y/ENTER: 消去     N/ESC: キャンセル",

	# --- Pause menu ---
	"PAUSED": "ポーズ",
	"Esc to resume / F10 settings": "Esc: 再開 / F10: 設定",
	"RESUME": "再開",
	"CONTROLS": "操作",
	"RETURN TO TITLE": "タイトルへ",
	"Esc / Enter: back": "Esc / Enter: 戻る",

	# --- Settings panel ---
	"SOUND & COMBAT FEEDBACK": "音と戦闘演出",
	"World paused. F10 / Esc: return. Click to change.": "世界は停止中。F10 / Esc: 戻る。クリックで変更。",
	"Effects volume": "効果音の音量",
	"Camera shake": "画面の揺れ",
	"Heavy-hit pause (45 ms)": "強撃のヒットストップ (45ms)",
	"Hit flashes": "被弾の点滅",
	"ON": "オン",
	"OFF": "オフ",
	"%d%% / CLICK +20%%": "%d%% / クリック +20%%",
	"Heavy impacts only. Aim and HUD stay steady. No full-screen flashes.": "強い一撃のみ。照準とHUDは揺れません。全画面の点滅はありません。",
	"Unreadable preferences preserved; changes apply for this session.": "設定を読み込めないため保持しました。変更はこの起動中のみ有効です。",
	"Could not save preferences. Applied for this session.": "設定を保存できませんでした。この起動中のみ有効です。",

	# --- Hub ---
	"STASH": "倉庫",
	"WARP GATE": "ワープゲート",
	"[E] OPEN STASH": "[E] 倉庫を開く",
	"[E] CHOOSE A MAP": "[E] 行き先を選ぶ",
	"HUNTER'S REST": "狩人の休息",
	"A quiet place between expeditions": "遠征の合間の静かな場所",

	# --- HUD ---
	"TOWN / HUNTER'S REST": "拠点 / 狩人の休息",
	"ABYSS / DEPTH %d": "深淵 / 深度%d",
	"%02d / %s": "%02d / %s",
	"VITALITY %d / %d": "体力 %d / %d",
	"LEVEL %d / XP %d OF %d": "Lv.%d / XP %d/%d",
	"BAG %d / STASH %d": "バッグ %d / 倉庫 %d",
	"MAPS %d / 3": "マップ %d / 3",
	"POTIONS %d / 3 [Q]": "ポーション %d / 3 [Q]",
	"[L] %s / %s": "[L] %s / %s",
	"LOOT SETTINGS": "回収設定",
	"DODGE READY": "回避 使用可",
	"DODGE %.1fs": "回避 %.1fs",
	"%s Lv.%d + %s Lv.%d / %s": "%s Lv.%d + %s Lv.%d / %s",
	"[F] BURST READY": "[F] バースト可",
	"HEAT %d%%": "熱量 %d%%",
	"PACT / %s": "契約 / %s",
	"%s / %s": "%s / %s",
	"RELIC / WAVE %d OF 3": "レリック / 3回中%d回目",
	"RELIC / NOVA PULL": "レリック / NOVA 引き寄せ",
	"RELIC / LANCE FORK": "レリック / LANCE 追加射線",
	"JOURNEY %d / 9  |  EMBERS %d  |  TALENTS %d  |  %d MIN  |  %s": "遠征 %d / 9  |  残火 %d  |  才能 %d  |  %d分  |  %s",
	"ABYSS CONQUERED": "深淵 制覇",
	"ABYSS DEPTH %d": "深淵 深度%d",
	"NEXT: CHAPTER %d - EXPEDITION %d": "次: 第%d章 - 遠征%d",
	"WASD Move  /  E Interact  /  I Inventory & Salvage  /  B Build & Forge  /  F10 Settings": "WASD 移動 / E 調べる / I 持ち物と分解 / B ビルドと鍛冶 / F10 設定",
	"WASD Move / Mouse Aim / LMB-Space Attack / Shift Dodge / F Burst / E Loot / Q Heal / T Town / I Bag / F10 Settings": "WASD 移動 / マウス 照準 / 左クリック・Space 攻撃 / Shift 回避 / F バースト / E 回収 / Q 回復 / T 帰還 / I 持ち物 / F10 設定",

	# --- Field / world labels ---
	"SEAL %s / %s": "封印 %s / %s",
	"BROKEN": "解除",
	"%d GUARDS": "守備隊 %d",
	"T / TOWN PORTAL": "T / 帰還ポータル",
	"WARD STONE": "守護石",
	"E / PICK UP": "E / 拾う",
	"CACHE / %d GUARDS": "宝箱 / 守備隊 %d",
	"WARD: 30% LESS DAMAGE": "守護: 被ダメージ30%減",
	"EXPOSED: +35% DAMAGE": "露出: 被ダメージ+35%",
	"PHASE %d": "フェーズ%d",
	"BOSS DEFEATED / COLLECT LOOT & RETURN": "守護者撃破 / 戦利品を回収して帰還",
	"SEALS %d / 2 / %d GUARDS": "封印 %d / 2 / 守備隊 %d",
	"SEAL BROKEN / DEFEAT THE GUARDIAN": "封印解除 / 守護者を倒せ",
	"BOSS": "守護者",
	"SEAL": "封印",
	"RELIC ACQUIRED / A NEW WAY TO FIGHT": "レリック入手 / 新たな戦い方",
	"Protected in your bag. I: inspect and equip.": "持ち物に入り保護済み。Iで確認と装備。",
	"CURSED CACHE": "呪われた宝箱",
	"GUARDS REMAINING / %d": "残りの守備隊 / %d",
	"CACHE CLAIMED": "宝箱 受取済み",
	"[E] CHOOSE YOUR REWARD": "[E] 報酬を選ぶ",
	"SHRINE / OPTIONAL": "祭壇 / 任意",
	"PACT TAKEN": "契約済み",
	"SHRINE DORMANT": "祭壇は眠っている",
	"[E] WEIGH THE COST": "[E] 代償を選ぶ",

	# --- Enemies and rooms ---
	"VOLATILE": "爆裂",
	"STORMCALLER": "嵐呼び",
	"SWIFT": "俊足",
	"DEATH BLAST": "死亡爆発",
	"AVOID MARKS": "予告範囲を回避",
	"+45% SPEED": "移動+45%",
	"ARRIVAL": "入口",
	"NARROW PASS": "狭路",
	"PILLAR HALL / SEAL I": "柱の広間 / 封印I",
	"ENCIRCLEMENT / SEAL II": "包囲広場 / 封印II",
	"CURSED VAULT / OPTIONAL": "呪われた宝物庫 / 任意",
	"GUARDIAN SANCTUM": "守護者の間",
	"APPROACH": "接近",
	"OPENING / ATTACK NOW": "隙 / 今攻撃",
	"SWEEP / GET BEHIND": "薙ぎ払い / 背後へ",
	"CHARGE / DODGE SIDEWAYS": "突進 / 横へ回避",
	"WARD STONES / BREAK TO EXPOSE": "守護石 / 壊して露出",
	"SOUL BEAM / LEAVE THE LINE": "魂の光線 / 射線から離れろ",
	"FIRE RING / FIND THE GREEN GAP": "火炎輪 / 緑の隙間へ",
	"CINDER MARKS / KEEP MOVING": "残火の標 / 動き続けろ",

	# --- Shrine offers ---
	"BERSERKER'S OATH": "狂戦の誓い",
	"Normal attacks +25%": "通常攻撃 +25%",
	"Potion healing -50%": "ポーション回復 -50%",
	"Strike harder; rely on dodging.": "強く叩き、回避に頼る。",
	"EMBER PACT": "残火の契約",
	"Heat gained +50%": "熱量獲得 +50%",
	"Damage taken +15%": "被ダメージ +15%",
	"Burst more often; take more risk.": "バーストを増やし、危険を取る。",
	"MARK OF GREED": "貪欲の印",
	"Guardian: +1 protected Rare": "守護者: 保護Rare +1",
	"Enemy life +25%": "敵HP +25%",
	"A longer fight for extra gear.": "長い戦いと引き換えに装備を。",
	"SHRINE OF BARGAINS / OPTIONAL": "代償付き祭壇 / 任意",
	"Choose one pact for this expedition. Take a benefit and its cost together.": "この遠征の契約を1つ選ぶ。利益と代償を同時に受ける。",
	"One pact per expedition. No switching. Ends on death or return to town.": "契約は1遠征1つ。変更不可。死亡・帰還で終了。",
	"Esc / E: leave without a pact. Available until the guardian fight begins.": "Esc / E: 契約せずに閉じる。守護者戦の開始まで選べる。",
	"ACCEPT / CLICK OR %d": "承諾 / クリックまたは%d",
	"Hit %.1f -> %.1f": "威力 %.1f → %.1f",
	"Potion %.1f -> %.1f HP": "ポーション %.1f → %.1f HP",
	"Heat %.0f -> %.0f / hit": "熱量 %.0f → %.0f / 命中",
	"100 damage -> 115 before armor": "被ダメージ100 → 防御前115",
	"Bonus Rare / Tier %d": "追加Rare / Tier %d",
	"All living & future enemies": "生存中と今後の敵すべて",

	# --- Waypoint (gate) panel ---
	"WAYPOINT / SELECT A DESTINATION": "ウェイポイント / 行き先を選ぶ",
	"Three expeditions per chapter. Break seals to reach the guardian.": "各章3遠征。封印を破り守護者へ挑む。",
	"CHAPTER %d / CLEARED %d OF 3": "第%d章 / 3遠征中%d達成",
	"RELIC %d/3: %s": "レリック %d/3: %s",
	"CLEAVE WAVE": "CLEAVE 衝撃波",
	"NOVA PULL": "NOVA 引き寄せ",
	"LANCE FORK": "LANCE 追加射線",
	"FIRST CHAPTER CLEAR: RELIC": "初回章クリア: レリック",
	"TRAVEL / CLICK OR %d": "出撃 / クリックまたは%d",
	"LOCKED / CLEAR PREVIOUS MAP": "未解放 / 前のマップをクリア",
	"ABYSS / COMPLETE CHAPTER 3": "深淵 / 第3章クリアで解放",
	"CALM / STANDARD": "穏やか / 標準",
	"FRENZY / +35% SPEED": "狂乱 / 速度+35%",
	"DREAD / +40% LIFE & +20% DAMAGE": "戦慄 / HP+40%・攻撃+20%",
	"Abyss contracts: extra item tier and double guardian embers. Click to cycle.": "深淵の危険条件: 装備Tier+1、守護者の残火2倍。クリックで切替。",
	"Esc / E to close   |   B: build & forge in town": "Esc / E: 閉じる   |   B: 拠点でビルドと鍛冶",

	# --- Cursed cache (trial) panel ---
	"CURSED CACHE / CHOOSE YOUR PRIZE": "呪われた宝箱 / 報酬を選ぶ",
	"Four marked guards awaken: +60% life and +25% damage. Kill all four to claim.": "印の守備隊4体が目覚める: HP+60%、攻撃+25%。全滅で受取。",
	"Optional encounter. Retreat is allowed; an unfinished cache gives no bonus reward.": "任意の挑戦。退却可能。未完了では追加報酬なし。",
	"GUARANTEED RARE / TIER %d": "Rare確定 / Tier %d",
	"Rune: %s": "ルーン: %s",
	"AWAKEN / CLICK OR %d": "目覚めさせる / クリックまたは%d",
	"+%d embers. Chosen gear goes directly to your bag and is protected from salvage.": "残火 +%d。選んだ装備は持ち物へ直接入り保護される。",
	"Only the marked guards count toward this challenge. No time limit.": "印の守備隊のみが対象。時間制限なし。",
	"Esc / E: leave the cache sealed": "Esc / E: 宝箱を封印したまま閉じる",

	# --- Equipment slots ---
	"WEAPON": "武器",
	"ARMOR": "防具",
	"CHARM": "護符",
	"Iron cleaver": "鉄の鉈",
	"Warden mail": "守人の鎧",
	"Ember charm": "残火の護符",
	"Cachebound Cleaver": "宝箱縛りの鉈",
	"Cachebound Mail": "宝箱縛りの鎧",
	"Cachebound Charm": "宝箱縛りの護符",
	"Common": "コモン",
	"Magic": "マジック",
	"Rare": "レア",
	"Relic": "レリック",

	# --- Inventory and stash panel ---
	"STASH & INVENTORY": "倉庫と持ち物",
	"INVENTORY": "持ち物",
	"[L] %s": "[L] %s",
	"SORT": "並べ替え",
	"SCRAP COMMON (%d)": "Common一括分解 (%d)",
	"SCRAP IN TOWN": "分解は拠点で",
	"EQUIPPED": "装備中",
	"BACKPACK": "持ち物",
	"PERSONAL STASH": "個人倉庫",
	"Click stored gear to take it out.": "倉庫の装備をクリックで取り出す。",
	"Shift-click backpack gear to store it.": "Shift＋クリックで持ち物を預ける。",
	"CHARACTER / LEVEL %d": "キャラクター / Lv.%d",
	"Skill hit           %.1f": "スキル威力          %.1f",
	"Maximum health      %d": "最大HP              %d",
	"Defense             %d": "防御                %d",
	"Attack interval     %.2fs": "攻撃間隔            %.2fs",
	"BURN %.0f%%/s / SLOW %.1f%% / HEAT +%.0f": "燃焼 %.0f%%/s / 減速 %.1f%% / 熱量 +%.0f",
	"Embers: %d / B: build & forge": "残火: %d / B: ビルドと鍛冶",
	"Hover: compare / Click: equip / Right-click: salvage / F or middle-click: protect / I: close": "ホバー: 比較 / クリック: 装備 / 右クリック: 分解 / F・中クリック: 保護 / I: 閉じる",
	"Hover: compare / F or middle-click: protect / Equip & salvage in town / I: close": "ホバー: 比較 / F・中クリック: 保護 / 装備と分解は拠点で / I: 閉じる",
	"%d ITEMS / %d": "%d個 / %d",
	"NEXT >": "次 >",
	"< PREV": "< 前",
	"Empty slot": "空きスロット",

	# --- Item tooltips ---
	"%s / %s / TIER %d": "%s / %s / Tier %d",
	"Attack damage": "攻撃力",
	"Maximum health": "最大HP",
	"Defense": "防御",
	"Attack speed %": "攻撃速度%",
	"%s: %d": "%s: %d",
	"Rune: %s / Forge +%d": "ルーン: %s / 鍛冶 +%d",
	"None": "なし",
	"No special effect": "特殊効果なし",
	"Magic and Rare gear can carry combat effects.": "MagicとRareは戦闘効果を持つ。",
	"%s / normal attacks": "%s / 通常攻撃",
	"Boss source: chapter %d / first clear or every 3 repeat kills": "入手: 第%d章 / 初回クリアまたは3撃破ごと",
	"Matching affixes stack across equipped slots.": "同じ接尾は装備部位をまたいで合算。",
	"PROTECTED / Cannot be salvaged": "保護中 / 分解不可",
	"F / middle-click: protect from salvage": "F / 中クリック: 分解保護",
	"Equipped": "装備中",
	"Click to take out": "クリックで取り出す",
	"Click to equip": "クリックで装備",
	"Equip after returning to town": "拠点で装備",
	" / Shift-click to store": " / Shift＋クリックで預ける",
	"ATK %d   HP %d   DEF %d   SPD %d%%": "攻撃 %d   HP %d   防御 %d   速度 %d%%",

	# --- Expeditions and chapters ---
	"The Fading Trail": "消えゆく道",
	"Ashbound Patrol": "灰縛りの巡回",
	"The First Seal": "第一の封印",
	"Voices Below": "地下の声",
	"The Silent Procession": "静かなる行列",
	"The Second Seal": "第二の封印",
	"Road of Cinders": "残燼の道",
	"The Broken Crown": "砕けた王冠",
	"The Last Flame": "最後の焚火",
	"ASHEN OUTSKIRTS": "灰の外縁",
	"BURIED SANCTUM": "埋葬聖域",
	"CINDER CITADEL": "残火の城塞",

	# --- Loot modes (HUD and pickup messages) ---
	"MANUAL": "手動",
	"AUTO": "自動",
	"AUTO + SCRAP": "自動＋分解",

	# --- Overlays and notices ---
	"THE LAST EMBER ENDURES": "最後の残火は消えない",
	"THE CINDER TYRANT HAS FALLEN": "残火の王は倒れた",
	"A SEAL SHATTERS": "封印が砕ける",
	"Depth 5 conquered. The flame is safe.": "深度5を制覇。焚火は守られた。",
	"The story is complete. The Abyss now opens at the town gate.": "物語は完結。深淵が拠点のゲートに開く。",
	"A skill-changing relic is in your bag. A new chapter awaits.": "スキルを変えるレリックが持ち物に。新たな章へ。",
	"Press any key, collect your loot, then T to return.": "任意のキーで閉じ、戦利品を拾いTで帰還。",
	"RESCUED FROM THE DEPTHS": "深淵より生還",
	"Collected gear and character progress are retained.": "回収した装備と成長は保持されます。",
	"Press R to return to town": "Rで拠点へ戻る",
	"MASTERY UP": "熟練アップ",
	"RELIC FOUND": "レリック入手",

	# --- Status messages ---
	"Save could not be loaded. Autosave disabled to preserve it.": "セーブを読み込めませんでした。保護のため自動保存を停止しました。",
	"Opening town portal... Stand still for 2 seconds.": "帰還ポータルを開いています… 2秒間静止してください。",
	"Portal cancelled. Stand still and press T to return.": "ポータルを中断しました。静止してTで帰還。",
	"Equipment updated. Your new stats apply immediately.": "装備を更新しました。新しい能力がすぐに反映されます。",
	"Equipment updated. Your new stats apply to the next expedition.": "装備を更新しました。次の遠征から新しい能力が適用されます。",
	"MAIN ROUTE / Break two guarded seals, then hunt %s. Purple vault: optional loot.": "主道 / 守られた封印を2つ破り、%s を狙え。紫の宝物庫は任意の戦利品。",
	"%s / %d kills / %d items / %d auto-salvaged. I: inspect your loot.": "%s / 撃破%d / 装備%d / 自動分解%d。Iで戦利品を確認。",
	"Rescued: gear retained": "生還: 装備は保持",
	"Returned to town": "拠点へ帰還",
	"Loot: %d collected / %d Common salvaged. I: inspect. L: pickup mode.": "回収: %d個取得 / Common %d個分解。Iで確認。Lで回収モード。",
	"Loot: %s%s": "回収: %s%s",
	" / Common drops become embers. Magic, Rare and favorites are kept.": " / Commonは残火に。Magic・Rare・保護品は保持。",
	" / E always collects nearby gear manually.": " / Eでは常に現物を手動回収。",
	"%s: %s": "%s: %s",
	"Protected from salvage": "分解から保護",
	"Protection removed": "保護を解除",
	"Backpack sorted: favorites, slot, rarity, then tier.": "持ち物を整理: 保護品→部位→レアリティ→Tier。",
	"Salvaged %d Common items / +%d embers. Favorites are protected.": "Common %d個を分解 / 残火 +%d。保護品は対象外。",
	"CURSED CACHE / Defeat four marked guards. You may retreat with T.": "呪われた宝箱 / 印の守備隊4体を倒せ。Tで退却できます。",
	"CURSED CACHE CLEARED / RARE %s DELIVERED": "呪われた宝箱 達成 / RARE %s を配布",
	"CACHE CLAIMED / %s + %d embers. Reward is in your bag, protected.": "宝箱 受取 / %s + 残火%d。報酬は保護されて持ち物に。",
	"WARD BROKEN / Sentinel exposed: +35% damage for 3 seconds.": "守護石 破壊 / 露出: 3秒間 被ダメージ+35%。",
	"SEAL %s BROKEN / Follow the main route.": "封印 %s 解除 / 主道を進め。",
	"Level %d! Permanent base stats increased.": "レベル%d! 基礎能力が上昇。",
	"GREED FULFILLED / BONUS RARE DELIVERED & PROTECTED": "貪欲 成就 / 追加RAREを保護して配布",
	"Guardian defeated! Rare loot: E. Return: T. Next journey is ready at the gate.": "守護者撃破! Rare回収: E。帰還: T。次の遠征はゲートで。",
	"The seal is broken. The guardian awaits at the eastern altar.": "封印は破られた。守護者は東の祭壇で待つ。",
	"The last flame is fading. B: choose your build. Walk to the gate and press E to begin.": "最後の焚火が消えゆく。Bでビルドを選び、ゲートでEを押して遠征へ。",
	"%s / %s / %s. This expedition only.": "%s / %s / %s。この遠征のみ。",
	"New Mod kept.": "新しいModを採用しました。",
	"Equipment changed; old item preserved.": "装備が変わったため、元の品を保持しました。",
	"Original Mod kept. Attempt cost consumed.": "元のModを保持しました。試行費用は消費済み。",

	# --- Build panel (skills, supports, talents) ---
	"THE EMBER GRIMOIRE": "残火の魔導書",
	"SKILLS & SUPPORTS": "スキルとサポート",
	"TALENTS & FORGE": "才能と鍛冶",
	"MOD CRAFTING": "Modクラフト",
	"EMBERS %d / POINTS %d": "残火 %d / 才能点 %d",
	"%s Lv.%d  +  %s Lv.%d": "%s Lv.%d  +  %s Lv.%d",
	"HIT %.1f / %.2fs / DPS %.1f": "威力 %.1f / %.2fs / DPS %.1f",
	"Click: equip / Hover: lore, comparison & next level / Kills train your linked pair / B: close": "クリック: 装備 / ホバー: 説明・比較・次のレベル / 撃破で装備中ペアが成長 / B: 閉じる",
	"TEMPER THE HUNTER": "狩人を鍛える",
	"Spend earned talent points. Reclaim them freely to try a different path.": "獲得した才能点を配分。無料で振り直して別の道を試せる。",
	"Salvage unwanted gear in your inventory; feed the embers into your equipment.": "不要な装備を分解し、残火を装備の強化へ。",
	"MIGHT": "剛力",
	"VITALITY": "体力",
	"TEMPO": "速さ",
	"%s %d / 6 [+]": "%s %d / 6 [+]",
	"+5 attack per point": "1点ごとに攻撃+5",
	"+20 life / +1 defense per point": "1点ごとにHP+20・防御+1",
	"+6% attack speed per point": "1点ごとに攻撃速度+6%",
	"%s +%d / %s": "%s +%d / %s",
	"MAX": "最大",
	"%d EMBERS": "残火%d",
	"RESET TALENTS / FREE": "才能リセット / 無料",
	"I: inventory / right-click gear to salvage / B: close": "I: 持ち物 / 右クリック: 分解 / B: 閉じる",
	"Lv.%d": "Lv.%d",
	"LOCK": "未解放",
	"LINKED": "リンク中",
	"MAX MASTERY": "熟練 最大",
	"%d / %d XP": "%d / %d XP",
	"UNLOCK / CLEAR CHAPTER 1": "解放 / 第1章クリア",
	"%.1f DMG  /  %.2fs  /  %.0f RANGE": "%.1f 威力 / %.2fs / %.0f 射程",
	"RELIC / Every third hit sends a wave": "レリック / 3回目の命中で衝撃波",
	"RELIC / Pull enemies into your nova": "レリック / NOVA前に敵を引き寄せ",
	"RELIC / Two extra piercing rays": "レリック / 追加の貫通射線2本",
	"%s / LEVEL %d OF %d": "%s / Lv.%d / %d",
	"WITH %s / CURRENT GEAR & RUNES": "%s / 現在の装備とルーン",
	"Hit %.1f  |  Interval %.3fs  |  DPS %.1f": "威力 %.1f | 間隔 %.3fs | DPS %.1f",
	"DPS vs equipped: %+.1f  /  Range %.0f": "装備中との差: %+.1f / 射程 %.0f",
	"Recovery %.2f%% life / landed attack": "回復 最大HPの%.2f%% / 命中時",
	"NEXT / LEVEL %d": "次 / Lv.%d",
	"Hit %.1f -> %.1f / Range %.0f -> %.0f": "威力 %.1f → %.1f / 射程 %.0f → %.0f",
	"MASTERED / Maximum level reached": "熟練 最大 / これ以上成長しない",
	"Kills train the equipped pair. Switching keeps progress.": "撃破で装備中のペアが成長。切り替えても経験は保持。",
	"DPS excludes burn, relic waves and additional targets.": "DPSは燃焼・レリックの追撃・複数対象を含まない。",
	"Clear chapter 1 to unlock this support.": "第1章クリアでこのサポートを解放。",
	"Click the card to equip in town. No currency cost.": "拠点でカードをクリックして装備。費用はかからない。",

	# --- Craft panel and Mod tooltips ---
	"Equip Magic or Rare gear to craft its Mods.": "MagicまたはRareを装備してModを加工。",
	"Common gear and Relics keep their own identity. I: equip a crafting base.": "CommonとRelicは加工対象外。Iで加工する装備を。",
	"%s / BASE TIER %d": "%s / 基礎Tier %d",
	"CRAFT RESULT / COST PAID": "加工結果 / 費用支払済み",
	"OLD: %s": "旧: %s",
	"NEW: %s": "新: %s",
	"ATK %d -> %d / LIFE %d -> %d": "攻撃 %d → %d / HP %d → %d",
	"DEF %d -> %d / SPD %d%% -> %d%%": "防御 %d → %d / 速度 %d%% → %d%%",
	"Closing keeps the old Mod. Materials are spent for the attempt; no refunds.": "閉じると元のModを保持。費用は試行時に消費、返却なし。",
	"%d-%d %s / selected Mod: 100%%": "%d-%d %s / 選択Mod: 100%%",
	"CRAFT / %d EMBERS%s": "加工 / 残火%d%s",
	" / NOT ENOUGH": " / 残火不足",
	"UNAVAILABLE / LOCK, TIER OR DUPLICATE": "実行不可 / ロック・Tier・重複",
	"UNLOCK SELECTED MOD": "選択Modのロック解除",
	"LOCK SELECTED MOD / FREE": "選択Modをロック / 無料",
	"Cost is spent on rolling. Keep new or old; no refund.": "数値抽選で費用を消費。新旧どちらかを採用、返却なし。",
	"Select slot -> Mod -> Tier. Only that slot changes. T1 is strongest; higher bases unlock it.": "枠 → Mod → Tier を選ぶ。選んだ枠のみ変化。T1が最強で、基礎Tierが高いほど解放。",
	"T%d%s": "T%d%s",
	" LOCKED": " ロック中",
	"P%d  ": "接頭%d  ",
	"S%d  ": "接尾%d  ",
	"Rare gear required": "Rareが必要",
	"%s / BASE T%d": "%s / 基礎T%d",
	"%s / %s / TEMPER +%d": "%s / %s / 鍛冶 +%d",
	"BASE: ATK %d / HP %d / DEF %d / SPD %d%%": "基礎: 攻撃 %d / HP %d / 防御 %d / 速度 %d%%",
	"PREFIX %s": "接頭 %s",
	"SUFFIX %s": "接尾 %s",
	"VS EQUIPPED: ATK %+d / HP %+d / DEF %+d / SPD %+d%%": "装備中との差: 攻撃 %+d / HP %+d / 防御 %+d / 速度 %+d%%",
	"B > MOD CRAFTING / T3 -> T2 -> T1": "B > Modクラフト / T3 → T2 → T1",
	"SALVAGE PROTECTED": "分解保護中",
	"Mod locks protect crafting slots, not the item from salvage.": "Modロックは加工枠の保護で、分解保護とは別。",

	# --- Mod content (item_mods.gd) ---
	"Might": "剛力",
	"Vitality": "体力",
	"Guard": "防御",
	"Tempo": "速度",
	"Scorching": "灼熱",
	"Frostbound": "凍縛",
	"Charged": "帯電",
	"attack": "攻撃",
	"life": "HP",
	"defense": "防御",
	"% speed": "% 速度",
	"% effect": "% 効果",
	"Empty Mod slot": "空のMod枠",
	" [LOCK]": " [ロック]",
	"Burn %.0f%%/s (2s)": "燃焼 %.0f%%/s (2秒)",
	"Slow %.1f%% (1.5s)": "減速 %.1f%% (1.5秒)",
	"+%.0f heat / hit": "熱量 +%.0f / 命中",
	"%s T%d / %s%s": "%s T%d / %s%s",
	"%s T%d / +%d %s%s": "%s T%d / +%d %s%s",

	# --- Skill content (skill_catalog.gd) ---
	"MELEE / ARC / BURST": "近接 / 扇状 / バースト",
	"Punish a guardian's opening.": "守護者の隙を突く。",
	"A blade tempered in the last campfire.": "最後の焚火で鍛えた刃。",
	"Sweeps a forward arc. Enemies behind you are safe.": "前方の扇状を薙ぎ払う。背後は安全。",
	"MELEE / AREA / CLEAR": "近接 / 範囲 / 殲滅",
	"Surround yourself. Cut a way out.": "囲まれても切り開く。",
	"The flame refuses to be surrounded.": "炎は囲まれることを拒む。",
	"Hits all nearby enemies, including those behind you.": "周囲の敵すべてに当たる。背後も含む。",
	"RANGED / LINE / PIERCE": "遠隔 / 直線 / 貫通",
	"Line up enemies at a safe distance.": "安全な距離から敵を並べて貫く。",
	"A splinter of dawn through the ash.": "灰を貫く暁の欠片。",
	"Pierces every enemy in a narrow forward line.": "前方の細い直線上の敵すべてを貫く。",
	"SUPPORT / DAMAGE": "補助 / 火力",
	"Heavy blows. Stronger burst windows.": "重い一撃。バーストが強くなる。",
	"Feed the flame. Make each strike count.": "炎に薪を。一撃を重く。",
	"Multiplies normal attack damage. No speed penalty.": "通常攻撃の威力を上げる。速度低下なし。",
	"+2 percentage points of damage per level.": "1レベルごとに威力+2ポイント。",
	"SUPPORT / SPEED": "補助 / 速度",
	"Trade hit damage for faster attacks.": "一撃の威力を落とし攻撃を速くする。",
	"The steel remembers its last strike.": "鋼は前の一撃を覚えている。",
	"Shortens attack intervals, but each hit deals 15% less.": "攻撃間隔を短縮。威力は15%減。",
	"Attack interval reduction grows 1.5 points per level.": "1レベルごとに間隔短縮+1.5ポイント。",
	"SUPPORT / RECOVERY": "補助 / 回復",
	"Stay in the fight by landing hits.": "命中で戦い続ける。",
	"From dying embers, a heartbeat returns.": "消えゆく残火から鼓動が戻る。",
	"Heals once per attack that connects. Deals 10% less.": "命中した攻撃ごとに1回回復。威力は10%減。",
	"+0.25% of maximum life recovered per level.": "1レベルごとに回復+最大HPの0.25%。",
	"+%.0f%% attack damage": "攻撃ダメージ +%.0f%%",
	"%.1f%% shorter attack interval": "攻撃間隔 -%.1f%%",
	"Recover %.2f%% life on hit": "命中時 最大HPの%.2f%% 回復",

	# --- Affix and relic content (item_effects.gd) ---
	"Hits burn for 20% hit damage/sec, for 2s.": "命中で2秒間、命中ダメージの20%/秒を燃焼。",
	"Hits slow movement by 15% for 1.5s.": "命中で1.5秒間、移動速度-15%。",
	"+4 heat per landed attack; once per swing.": "命中した攻撃ごとに熱量+4。1振り1回。",
	"CLEAVE: every 3rd landed swing sends a wave.": "CLEAVE: 3回目の命中で衝撃波。",
	"Wave: 300 range, 75% hit damage. No double hit.": "衝撃波: 射程300、威力75%。二重ヒットなし。",
	"NOVA: pull nearby enemies before striking.": "NOVA: 攻撃前に近くの敵を引き寄せる。",
	"Pull: 250 range, 90 distance. Bosses resist.": "引き寄せ: 射程250、距離90。ボスには無効。",
	"LANCE: fire two additional piercing rays.": "LANCE: 貫通射線を2本追加。",
	"Side rays: +/-22 degrees, 60% hit. No overlap.": "追加射線: 左右22度、威力60%。重複なし。",

	# --- Skill link UI and new skill ---
	"RANGED / PROJECTILE / FIRE": "遠隔 / 投射物 / 火",
	"Fire bolts down a safe lane.": "安全な位置から火弾を放つ。",
	"A spark that refuses to die.": "消えない火花。",
	"Fires a bolt of embers. Projectile supports change how it flies.": "残火の弾を放つ。投射物サポートで挙動が変わる。",
	"PROJECTILE": "投射物",
	"AREA": "範囲",
	"ATTACK": "攻撃",
	"PHYSICAL / FIRE": "物理 / 火",
	"Projectiles +2, each 40% less damage": "投射物 +2、各 -40% 威力",
	"Projectiles pierce 2 extra enemies": "投射物が敵を2体追加で貫通",
	"Hits chain to 2 nearby enemies": "命中後、近くの敵2体へ連鎖",
	"Area +35%, 10% less damage": "範囲 +35%、威力 -10%",
	"Area -30%, 25% more damage": "範囲 -30%、威力 +25%",
	"30% more damage, 10% slower attacks": "威力 +30%、攻撃速度 -10%",
	"25% faster attacks, 10% less damage": "攻撃速度 +25%、威力 -10%",
	"Hits burn for 20% damage/sec for 2s": "命中で2秒間、威力の20%/秒を燃焼",
	"Recover 2% of maximum life per hit": "命中で最大HPの2%回復",
	"+4 heat per hit": "命中で熱量 +4",
	"SUPPORT SLOTS %d / %d": "サポート枠 %d / %d",
	"SUPPORT POOL": "サポート一覧",
	"EMPTY SLOT / CLICK A SUPPORT": "空き枠 / サポートを選択",
	"LOCKED / REACH SKILL LEVEL %d": "ロック中 / スキルLv.%dで解放",
	"CLICK TO LINK": "クリックで装着",
	"SLOTS FULL": "枠が満杯",
	"TAG: %s": "タグ: %s",
	"TAGS: %s": "タグ: %s",
	"SUPPORT / REQUIRES %s": "サポート / 必要タグ %s",
	"APPLIES TO: %s": "適用先: %s",
	"Supports have no levels. One copy of each may be linked.": "サポートはレベル無し。同種は1つまで装着できる。",
	"Click to link or unlink. Slots open as the skill levels up.": "クリックで装着・解除。スキルレベルで枠が増える。",
	"SLOTS %d / %d": "枠 %d / %d",
	"Linked supports are included in these numbers.": "装着中サポート込みの数値。",
	"Kills train the equipped skill. Switching keeps progress.": "撃破で装備中スキルが成長。切り替えても経験は保持。",
	"Click to equip in town. Supports are pruned if they no longer apply.": "拠点でクリックして装備。適用外のサポートは外れる。",
	"NO SUPPORTS LINKED": "サポート未装着",
	"Click a skill to equip / Click a support to link or unlink / B: close": "スキルをクリックで装備 / サポートをクリックで装着・解除 / B: 閉じる",
	"%.1f DMG / %.2fs / %.0f RANGE": "%.1f 威力 / %.2fs / %.0f 射程",
	"LEVEL %d": "Lv.%d",
	"PROJECTILES +%d": "投射物 +%d",
	"PIERCE +%d": "貫通 +%d",
	"CHAIN +%d": "連鎖 +%d",
	"AREA %d%%": "範囲 %d%%",
	"BURN": "燃焼",
	"LEECH": "吸血",
	"HEAT +%d": "熱量 +%d",
	"%s Lv.%d  |  HIT %.1f / %.2fs / DPS %.1f": "%s Lv.%d | 威力 %.1f / %.2fs / DPS %.1f",
	"%s Lv.%d / SUPPORTS %d/%d / %s": "%s Lv.%d / サポート %d/%d / %s",

	# --- Training ground and build presets ---
	"TRAINING": "試し斬り場",
	"TRAINING GROUND": "試し斬り場",
	"[E] TRAINING GROUND": "[E] 試し斬り場",
	"TRAINING GROUND / %.1fs": "試し斬り場 / %.1fs",
	"TOTAL %d  /  DPS %d  /  BURN %d  /  HITS %d": "合計 %d / DPS %d / 燃焼 %d / 命中 %d",
	"TRAINING GROUND / Attack the posts. R: reset the meter. T: return to town.": "試し斬り場 / 標的を攻撃。Rで計測リセット、Tで拠点へ。",
	"TRAINING GROUND / Attack the posts. B: change your build. R: reset the meter. T: return to town.": "試し斬り場 / 標的を攻撃。Bでビルド変更、Rで計測リセット、Tで拠点へ。",
	"Mod crafting is only available in town.": "Modクラフトは拠点でのみ行えます。",
	"SAVE": "保存",
	"LOAD": "読込",
	"EMPTY": "空き",
	"Preset %d saved.": "プリセット%dを保存しました。",
	"Preset %d loaded.": "プリセット%dを読み込みました。",

	# --- Objective tracker ---
	"GOAL: travel from the warp gate": "目標: ワープゲートから出撃",
	"GOAL: check your build with B, then travel at the gate": "目標: Bでビルドを確認し、ゲートから出撃",
	"TRAINING GROUND / Attack the posts (R: reset)": "試し斬り場 / 標的を攻撃（R: リセット）",
	"GOAL: collect loot and return with T": "目標: 戦利品を回収し T で帰還",
	"GOAL: break the seals / %d guards left": "目標: 封印を破れ / 守備隊 残り%d",
	"GOAL: defeat the guardian": "目標: 守護者を倒せ",
	"SUPPORTS %d / %d": "サポート %d / %d",

	# --- Passive tree ---
	"PASSIVES": "パッシブ",
	"PASSIVE POINTS %d / %d": "パッシブ点 %d / %d",
	"EMBERS %d / POINTS %d / PASSIVE %d": "残火 %d / 才能点 %d / パッシブ点 %d",
	"RESET PASSIVES / FREE": "パッシブをリセット / 無料",
	"Click to allocate / Right-click to refund / One point per level": "クリックで取得 / 右クリックで取消 / 1レベルにつき1点",
	"ONLY HELPS SKILL TAGS: %s": "対応スキルタグ: %s",
	"START": "起点",
	"ALLOCATED": "取得済み",
	"CLICK TO ALLOCATE": "クリックで取得",
	"NEEDS THE PREVIOUS NODE": "前のノードが必要",
	"NO POINTS LEFT": "ポイント不足",
	"Right-click to refund. Nodes further down must be refunded first.": "右クリックで取消。先のノードから順に取消してください。",
	"Passive allocated.": "パッシブを取得しました。",
	"Passive refunded.": "パッシブを取り消しました。",
	"Passives reset.": "パッシブをリセットしました。",
	"The root. Three paths branch from here.": "起点。ここから3系統に分岐する。",
	"Damage +8%": "威力 +8%",
	"Projectile skills deal +18% damage": "投射物スキルの威力 +18%",
	"Projectiles +1": "投射物 +1",
	"Area skills gain +15% area": "範囲スキルの範囲 +15%",
	"Melee skills deal +20% damage": "近接スキルの威力 +20%",
	"Maximum life +40": "最大HP +40",
	"Defense +5": "防御 +5",
	"Maximum life +80": "最大HP +80",
	"Damage taken -6%": "被ダメージ -6%",
	"Dodge cooldown -20%": "回避の再使用 -20%",
	"Movement speed +6%": "移動速度 +6%",
	"Heat gained +25%": "熱量獲得 +25%",
	"Burn damage +25%": "燃焼ダメージ +25%",
	"Recover +1.5% life per hit": "命中回復 +1.5%",
	"Attack speed +8%": "攻撃速度 +8%",
	"Maximum mana +60": "最大マナ +60",
	"Mana regeneration +2.5/s": "マナ回復 +2.5/s",
	"SPIRIT": "精神",
	"+15 mana / +1 regen per point": "1点ごとに最大マナ+15・回復+1",

	# --- Active abilities ---
	"Pierce a line of enemies with a burning spear.": "燃える槍で直線上の敵を貫く。",
	"Scorch the ground, burning and slowing enemies inside.": "地面を焼き、範囲内の敵を燃焼・減速させる。",
	"Gain a shield that absorbs damage for 5 seconds.": "5秒間、ダメージを吸収するシールドを得る。",
	"Gain attack speed and movement speed for 5 seconds.": "5秒間、攻撃速度と移動速度が上がる。",

	# --- Slot assignment UI ---
	"SLOTS": "スロット",
	"SUPPORTS": "サポート",
	"BASIC ATTACK  (CLICK / SPACE)": "基本攻撃（左クリック / Space）",
	"ACTIVE SLOTS  (1-4)": "アクティブ枠（1〜4）",
	"SKILL POOL  /  PICK A SLOT, THEN A SKILL": "スキル一覧 / 枠を選んでからスキルを選択",
	"Attack skills can also sit in active slots. Each skill fills only one slot.": "攻撃スキルもアクティブ枠に置けます。同じスキルは1枠だけ。",
	"Supports follow the basic attack; active skills scale with your attack.": "サポートは基本攻撃に付きます。アクティブは攻撃力で伸びます。",
	"BASIC": "基本",
	"KEY %d": "キー%d",
	"SLOT %d / LOCKED UNTIL Lv.%d": "枠%d / Lv.%dで解放",
	"SLOT %d / EMPTY": "枠%d / 空き",
	"COOLDOWN %.0fs": "再使用 %.0fs",
	"COOLDOWN %.0fs / MANA %d": "再使用 %.0fs / マナ%d",
	"Lv.%d / COOLDOWN %.0fs / MANA %d": "Lv.%d / 再使用 %.0fs / マナ%d",
	"%s Lv.%d  |  HIT %.1f / %.2fs": "%s Lv.%d | 威力 %.1f / %.2fs",
	"MANA %d / %d": "マナ %d / %d",
	"Not enough mana.": "マナが足りません。",
	"SUPPORTS FOR %s": "%s のサポート",
	"ACTIVE / COOLDOWN %.1fs": "アクティブ / 再使用 %.1fs",
	"ACTIVE / COOLDOWN %.1fs / MANA %d": "アクティブ / 再使用 %.1fs / マナ%d",
	"Damage scales with attack and untagged passives.": "威力は攻撃力とタグなしパッシブで伸びる。",
	"Assign it to any active slot.": "好きなアクティブ枠に割り当てられる。",
	"Basic attack set to %s.": "基本攻撃を %s にしました。",
	"Only attack skills can fill the basic slot.": "基本枠には攻撃スキルだけを置けます。",
	"Slot %d set to %s.": "枠%dを %s にしました。",
	"That skill is locked or already assigned.": "そのスキルは未解放か、すでに別枠です。",

	# --- Per-skill support links ---
	"SUPPORTS / %s": "%s のサポート",
	"%s  %s": "%s  %s",
	"%s  |  HIT %.1f / %.2fs": "%s | 威力 %.1f / %.2fs",
	"%s  T%d": "%s T%d",
	"LINKED HERE": "この枠に装着",
	"USED IN %s": "%s で使用中",
	"LINKED AT %s / TIER %d": "%s に装着 / Tier %d",
	"Right-click a link to upgrade (cost %d embers).": "右クリックでリンクを強化（残火%d）。",
	"Already at the strongest tier.": "これ以上強化できません。",
	"Support linked.": "サポートを装着しました。",
	"Support unlinked.": "サポートを外しました。",
	"Cannot link that support here.": "この枠には装着できません。",
	"Support upgraded to the next tier.": "サポートを1段階強化しました。",
	"Not enough embers or already upgraded.": "残火不足か、これ以上強化できません。",

	# --- Auras and spirit ---
	"AURAS": "オーラ",
	"SPIRIT %d / %d": "霊力 %d / %d",
	"RESERVE %d": "予約 %d",
	"Reserved auras stay on while you fight.": "予約したオーラは戦闘中ずっと有効。",
	"Only reserved auras are active. Click to toggle; the spirit pool grows with level.": "予約したオーラだけが有効。クリックで切替。霊力はレベルで増える。",
	"Damage +15%": "威力 +15%",
	"Defense +8": "防御 +8",
	"Mana regeneration +3/s": "マナ回復 +3/s",
	"Movement speed +8%": "移動速度 +8%",
	"Aura updated.": "オーラを有効にしました。",
	"Aura disabled.": "オーラを解除しました。",
	"Not enough spirit.": "霊力が足りません。",
}

static func t(source: String) -> String:
	return JA.get(source, source)
